project:
  type: book
  preview:
    port: 4200
    browser: false

book:
  title: "The Sovereign Individual"
  output-file: main
  subtitle: "De overgang naar het informatietijdperk"
  author: "James Dale Davidson & Lord William Rees-Mogg"
  date: "9/10/2024"
  image: cover.png
  image-alt: "The Sovereign Individual"
  isbn: 978-9916-000-00-0
  language: en
  original-title: "The Sovereign Individual"
  publisher: Konsensus Network
  original-publisher: Simon & Schuster
  favicon: /figures/freestarfish.png
  repo-url: https://github.com/konsensusnetwork/TSI_EN
  repo-actions: [edit, source]
  search:
    location: sidebar
    type: overlay
  sidebar:
    style: floating
    border: true
  navbar:
    left:
      - icon: book
        text: "Read online"
        href: index.qmd
        aria-label: Book
      - icon: shop
        text: "Get the paperback in Presale!"
        href: https://bitcoinbook.shop/products/das-souverane-individuum
        aria-label: Shop
  page-footer:
    left:
      - text: "Â© 2024 Konsensus Network"
    center:
      - text: "License"
        href: index.qmd
      - text: "About the publisher"
        href: publisher.qmd
      - text: "Presale"
        href: presale.qmd
    right:
      - icon: twitter
        href: https://twitter.com/konsensusn
        aria-label: Twitter
      - icon: github
        href: https://github.com/konsensusnetwork
        aria-label: Github
      - icon: linkedin
        href: https://www.linkedin.com/konsensusnetwork
        aria-label: LinkedIn
      - icon: youtube
        href: https://www.youtube.com/konsensusnetwork
        aria-label: YouTube
  open-graph: true
  twitter-card:
    site: "@konsensusn"
  chapters:
    - index.qmd
    - chapters/ch01.qmd
    - chapters/ch02.qmd
    - chapters/ch03.qmd
    - chapters/ch04.qmd
    - chapters/ch05.qmd
    - chapters/ch06.qmd
    - chapters/ch07.qmd
    - chapters/ch08.qmd
    - chapters/ch09.qmd
    - chapters/ch10.qmd
    - chapters/ch11.qmd

format:
  html:
    lang: en
    theme:
      light: [flatly, theme.scss, theme-light.scss]
    number-depth: 2
    grid:
      sidebar-width: 500px
      body-width: 900px
      margin-width: 350px
      gutter-width: 1em
    toc: true
    toc-location: left
    reference-location: margin
  pdf:
    lang: en
    documentclass: memoir
    classoption: smalldemyvopaper,10pt,twoside,onecolumn,openright,extrafontsizes,hidelinks
    papersize: a5
    toc-depth: 1
    toc-title: Contents
    keep-tex: true
    colorlinks: false
    include-in-header:
      - preamble.tex
  epub:
    cover-image: cover.png
    cover-image-alt: |
      The Sovereign Individual book cover
    creator: Konsensus Network
    toc: true
    toc-depth: 1
    toc-title: Contents
    lang: "en-US"
    css: epub.css
    number-depth: 2