project:
  type: book

book:
  title: "The Sovereign Individual"
  subtitle: "Mastering the Transition to the Information AGe"
  author: "James Dale Davidson & Lord William Rees-Mogg"
  date: "9/16/2024"
  cover-image: cover.png
  isbn: 978-3-16-123450-0
  license: CC-BY-4.0
  language: en
  publisher: Simon & Schuster New Yrok
  navbar:
    logo: cover.png
    logo-alt: Cover
    right:
      - icon: github
        href: https://github.com/konsensusnetwork/TSI_EN
        aria-label: GitHub
      - icon: shop
        href: https://bitcoinbook.shop/
        aria-label: Shop
  page-footer:
    center:
      - text: "License"
        href: index.qmd
  open-graph: true
  twitter-card:
    site: "@konsensusn"
  chapters:
    - index.qmd
    - chapters/ch01.qmd
    - chapters/ch02.qmd
    - chapters/ch03.qmd
    - chapters/ch04.qmd
    - chapters/ch05.qmd
    - chapters/ch06.qmd
    - chapters/ch07.qmd
    - chapters/ch08.qmd
    - chapters/ch09.qmd
    - chapters/ch10.qmd
    - chapters/ch11.qmd

format:
  html:
    theme: cosmo
    number-depth: 1
    reader-mode: true
  latex:
    documentclass: memoir
    classoption: smalldemyvopaper,11pt,twoside,onecolumn,openright,extrafontsizes
    papersize: a5
    secnumdepth: 1
    geometry:
      - top=18mm
      - bottom=28mm
      - left=18mm
      - right=18mm
    epub:
      creator: Konsensus Network




